### ISSUE TITLE
theme editor in the front

### ISSUE THREAD

**Issue by demeldoo** [cscart/cscart-boilerplate#4]
theme editor is not showing in the frontend

**Comment by amelekesov** [comment]
Unfortunately, we haven't adapted the Theme Editor for this theme yet.

**Comment by WorckOleg** [comment]
Why don't you use less bootstrap version?
https://github.com/twbs/bootstrap/tree/master/less

**Comment by drahosistvan** [comment]
@WorckOleg: There is an opened issue (#26) for this request.

**Comment by matthewmorek** [comment]
I would prefer to keep Theme Editor support separate from the boilerplate theme, since it's not necessary in some cases.

An obvious example is when a theme is being purpose-built for a single store, without the intention to provide customisation via Theme Editor to the store owner (so they would not ruin the design, etc).

**Comment by eermol** [comment]
@demeldoo , @matthewmorek , from CS-Cart 4.3.6 Theme Editor has been moved in admin area, so at the moment theme will work fine if you will add "Styles" with less variables.  (from last week we decided to remove styles folder because she was empty)

**Comment by eermol** [comment]
@demeldoo , @matthewmorek , Theme editor working will be added in CS-Cart 4.3.7. So if u have another version you can't use Theme editor in Boilerplate
