### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by thanasisloi7** [cscart/cscart-boilerplate#46]
If product have many images when you open the product we see the first image when we choose the second one image hidden, i found this part of code that in the include file class is hidden.

<div class="thumbnail product-img cm-preview-wrapper">
{include file="common/image.tpl" obj_id="`$preview_id`_`$image_id`" images=$image_pair_var link_class="cm-image-previewer" image_width=$image_width image_height=$image_height image_id="preview[product_images_`$preview_id`]"}

{foreach from=$product.image_pairs item="image_pair"}
    {if $image_pair}
        {if $image_pair.image_id}
            {assign var="img_id" value=$image_pair.image_id}
        {else}
            {assign var="img_id" value=$image_pair.detailed_id}
        {/if}
        {include file="common/image.tpl" images=$image_pair link_class="cm-image-previewer hidden" obj_id="`$preview_id`_`$img_id`" image_width=$image_width image_height=$image_height image_id="preview[product_images_`$preview_id`]"}
    {/if}
{/foreach}
</div>

**Comment by eermol** [comment]
@thanasisloi7 thank you for the reply. 
Fixed by this [commit](https://github.com/cscart/cscart-boilerplate/commit/a98a90695bd4dd61a4fce3d774e9f23fff13c342) 
Bootstrap have some controversial moment with "hidden" class that have !important for display:none. 
I want to attract your attention that we add our custom class ".invisible" with normal display:none
